# -*- coding: utf-8 -*-
"""312110544-Mirnawati-steganography

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BLGRyTInYOOEuQZDmsyWkVLTB54-8Hbe
"""

# Install modul stegano
!pip install stegano

from google.colab import files
from stegano import lsb
from PIL import Image

# Fungsi untuk mengunggah file gambar
def upload_image():
    uploaded = files.upload()
    file_name = list(uploaded.keys())[0]
    return file_name

# Mengunggah file gambar
image_file = upload_image()

# Mengekstrak pesan rahasia dari gambar hasil steganografi
revealed_message = lsb.reveal(Image.open(image_file))

# Menampilkan pesan rahasia yang diekstrak
print("Pesan rahasia yang diekstrak:", revealed_message)